name: Check Permissions
on:
  workflow_call:
    inputs:
      github-event-name:
        required: true
        type: string
defaults:
  run:
    shell: bash -euo pipefail {0}
permissions: {}
jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      run: 'echo "uses: Harden the runner (Audit all outbound calls)"'
    - name: Disallow CI runs on PRs from forks
      if: |
        inputs.github-event-name  == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository
      run: 'echo "run: Disallow CI runs on PRs from forks"'
